version: "2"
services:
  doc-loader:
    build: .
    image: challisa/doc-loader
    container_name: doc-loader
    ports:
      - 8000:8000
    volumes:
      - .:/opt/working
    entrypoint: sleep 100000 # pip install -r docs/requirements.txt && mkdocs serve --dev-addr 0.0.0.0:8000
